import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, setPersistence, browserLocalPersistence, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup, GoogleAuthProvider, linkWithCredential, signOut, sendPasswordResetEmail, updateProfile } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore, collection, query, where, orderBy, limit, getDocs, addDoc, deleteDoc, doc, setDoc, getDoc, runTransaction, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';

const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getFirestore(app), googleProvider=new GoogleAuthProvider();
const authPersistenceReady=setPersistence(auth,browserLocalPersistence).catch(()=>{});
let currentUser=null, accountReady=false, applyingRemote=false, pendingGoogleCredential=null, authState='AUTH_LOADING', authLoadToken=0, authLoadError='';
const $=s=>document.querySelector(s);
const keys={coins:'chroma-coins',xp:'chroma-xp',shop:'chroma-shop',name:'chroma-name',username:'chroma-username',photo:'chroma-profile-photo',gender:'chroma-profile-gender',streak:'chroma-daily-streak',levelRewards:'chroma-level-rewards',redeemedCodes:'chroma-redeemed-codes',missions:'chroma-missions',ranking:'chroma-ranking',ranked:'chroma-ranked',mailRead:'chroma-mail-read',friends:'chroma-friends'};
const defaultShop=()=>({owned:[],equipped:{profile:'',cards:'','name-effect':'', 'profile-theme':'','profile-badge':''},potions:[]});
function json(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch(e){return fallback;}}
function localState(){const shop=json(keys.shop,defaultShop()),name=localStorage.getItem(keys.name)||'';let rank='Prata I';try{if(typeof rankedStats==='function'&&typeof rankedTier==='function'){const tier=rankedTier(rankedStats(name).points);rank=tier.name+' '+tier.level;}}catch(e){}return {coins:Number(localStorage.getItem(keys.coins)||0)||0,xp:Number(localStorage.getItem(keys.xp)||0)||0,level:typeof levelFromXP==='function'?levelFromXP(Number(localStorage.getItem(keys.xp)||0)||0):1,rank,cosmetics:Array.isArray(shop.owned)?shop.owned:[],equipped:shop.equipped||{},shop,name,username:localStorage.getItem(keys.username)||'',photo:localStorage.getItem(keys.photo)||'',gender:localStorage.getItem(keys.gender)||'',streak:json(keys.streak,{day:0,lastClaim:null}),levelRewards:json(keys.levelRewards,[]),redeemedCodes:json(keys.redeemedCodes,[]),missions:json(keys.missions,null),ranking:json(keys.ranking,[]),ranked:json(keys.ranked,[]),mailRead:json(keys.mailRead,[]),friends:json(keys.friends,{friends:[],requests:[],sent:[]}),gameStats:json('chroma-game-stats',{}),showcaseAchievements:json('chroma-showcase-achievements',[]),cardsPlayed:Number(localStorage.getItem('chroma-cards-played')||0)||0,flags:{psicopata:localStorage.getItem('chroma-flag-psicopata')==='1'}};}
function writeLocal(data){if(data.coins!=null)localStorage.setItem(keys.coins,String(data.coins));if(data.xp!=null)localStorage.setItem(keys.xp,String(data.xp));if(data.shop)localStorage.setItem(keys.shop,JSON.stringify({...defaultShop(),...data.shop,equipped:{...defaultShop().equipped,...(data.shop.equipped||{})}}));for(const k of ['streak','levelRewards','redeemedCodes','missions','ranking','ranked','mailRead','friends'])if(data[k]!==undefined)localStorage.setItem(keys[k],JSON.stringify(data[k]));if(data.gameStats!==undefined)localStorage.setItem('chroma-game-stats',JSON.stringify(data.gameStats));if(data.showcaseAchievements!==undefined)localStorage.setItem('chroma-showcase-achievements',JSON.stringify(data.showcaseAchievements));if(data.cardsPlayed!=null)localStorage.setItem('chroma-cards-played',String(data.cardsPlayed));if(data.flags?.psicopata!=null)localStorage.setItem('chroma-flag-psicopata',data.flags.psicopata?'1':'0');for(const k of ['name','username','photo','gender'])if(data[k]!==undefined)localStorage.setItem(keys[k],data[k]||'');}
function accountMessage(text,error=false){const el=$('#accountMsg');if(el){el.textContent=text;el.className='account-msg'+(error?' error':'');}}
function friendlyError(e){const code=String(e&&e.code||'').toLowerCase();if(code.includes('email-already-in-use'))return'Este e-mail já está cadastrado.';if(code.includes('invalid-credential')||code.includes('wrong-password')||code.includes('user-not-found'))return'E-mail ou senha incorretos.';if(code.includes('weak-password'))return'A senha precisa ter pelo menos 6 caracteres.';if(code.includes('invalid-email'))return'Digite um e-mail válido.';if(code.includes('popup-closed-by-user'))return'A janela do Google foi fechada antes da conclusão.';if(code.includes('popup-blocked'))return'O navegador bloqueou a janela do Google. Permita pop-ups para este site.';if(code.includes('unauthorized-domain'))return'Este domínio ainda não está autorizado no Firebase Authentication.';if(code.includes('operation-not-allowed'))return'O login por Google ainda não está ativado no Firebase.';if(code.includes('permission-denied'))return'Sua conta está autenticada, mas o Firebase recusou esta operação por falta de permissão.';if(code.includes('unavailable')||code.includes('deadline-exceeded')||code.includes('network'))return'Não foi possível conectar ao servidor. Verifique sua conexão e tente novamente.';if(code.includes('failed-precondition'))return'O Firebase não está configurado para concluir esta operação.';return e&&e.message||'Não foi possível concluir a operação.';}
function canWrite(){return authState==='AUTHENTICATED'&&!!currentUser&&accountReady;}
function authUnavailableMessage(){return authState==='AUTH_LOADING'?'Aguarde a confirmação da sua sessão…':authState==='UNAUTHENTICATED'?'Entre na sua conta para continuar.':authLoadError||'A conta está autenticada, mas ainda está sincronizando. Aguarde um instante.';}
function usernameFromUser(user){return String(user.displayName||user.email?.split('@')[0]||'jogador').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_]/g,'').slice(0,18)||'jogador';}
function defaultProfile(user){const shop=defaultShop();return {uid:user.uid,email:user.email||'',username:usernameFromUser(user),coins:0,xp:0,level:1,rank:'Prata I',cosmetics:[],equipped:{},shop,name:user.displayName||'',photo:user.photoURL||'',gender:'',streak:{day:0,lastClaim:null},levelRewards:[],redeemedCodes:[],missions:null,ranking:[],ranked:[],mailRead:[],friends:{friends:[],requests:[],sent:[]},gameStats:{},showcaseAchievements:[],cardsPlayed:0,flags:{psicopata:false},createdAt:serverTimestamp(),updatedAt:serverTimestamp()};}
function cloudPayload(){const s=localState();return {...s,uid:currentUser.uid,email:currentUser.email||'',cosmetics:Array.isArray(s.shop?.owned)?s.shop.owned:[],equipped:s.shop?.equipped||{},updatedAt:serverTimestamp()};}
function updateAccountUI(){window.firebaseCurrentUserEmail=currentUser&&currentUser.email||'';window.firebaseCurrentUserUid=currentUser&&currentUser.uid||'';window.firebaseAuthState=authState;window.firebaseAuthError=authLoadError;const status=$('#accountStatus'),open=$('#accountOpen'),out=$('#accountLogout');if(status)status.textContent=authState==='AUTH_LOADING'?'Verificando sessão…':authState==='AUTHENTICATED'?'Conta: '+(currentUser?.email||'conectada'):'Progresso local — entre para salvar na nuvem';if(open){open.textContent=authState==='AUTH_LOADING'?'Verificando sessão…':authState==='AUTHENTICATED'?'Gerenciar conta':'Entrar ou criar conta';open.disabled=authState==='AUTH_LOADING';}if(out)out.hidden=authState!=='AUTHENTICATED';document.documentElement.classList.toggle('firebase-ready',canWrite());}
async function ensureProfile(user){const ref=doc(db,'users',user.uid);let profile;await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists()){profile=defaultProfile(user);tx.set(ref,profile);return;}profile=snap.data();const missing={};if(profile.uid==null)missing.uid=user.uid;if(profile.email==null)missing.email=user.email||'';if(profile.username==null)missing.username=usernameFromUser(user);if(profile.level==null)missing.level=1;if(profile.rank==null)missing.rank='Prata I';if(profile.cosmetics==null)missing.cosmetics=[];if(profile.equipped==null)missing.equipped={};if(Object.keys(missing).length)tx.set(ref,{...missing,updatedAt:serverTimestamp()},{merge:true});});return profile;}
async function loadAccount(user,token){currentUser=user;accountReady=false;updateAccountUI();if(!user)return;const profile=await ensureProfile(user);if(token!==authLoadToken||currentUser?.uid!==user.uid)return;const snap=await getDoc(doc(db,'users',user.uid));const data=snap.exists()?snap.data():profile;applyingRemote=true;writeLocal(data);applyingRemote=false;accountReady=true;updateAccountUI();refreshGameAfterCloud();publishSocialProfile().catch(()=>{});if(typeof window.renderSocial==='function')window.renderSocial();if(typeof window.renderClan==='function')window.renderClan();accountMessage('Conectado. Seu progresso será salvo na nuvem.');}
async function persistState(){if(!canWrite())throw new Error(authUnavailableMessage());await setDoc(doc(db,'users',currentUser.uid),cloudPayload(),{merge:true});}
async function syncToCloud(){if(!canWrite()||applyingRemote)return;try{await persistState();}catch(e){await restoreFromServer().catch(()=>{});accountMessage(friendlyError(e),true);}}
function refreshGameAfterCloud(){try{if($('#inName'))$('#inName').value=localStorage.getItem(keys.name)||'';if($('#profileGender'))$('#profileGender').value=localStorage.getItem(keys.gender)||'';const photo=localStorage.getItem(keys.photo)||'';if(photo&&$('#profilePreview'))$('#profilePreview').innerHTML='<img src="'+photo.replace(/"/g,'&quot;')+'" alt="Foto de perfil">';if(typeof updateCoinHud==='function')updateCoinHud(false);if(typeof renderProfileXP==='function')renderProfileXP();if(typeof updateModeLockUI==='function')updateModeLockUI();if(typeof applyCosmetics==='function')applyCosmetics();if(typeof renderShop==='function')renderShop();if(typeof renderProfile==='function')renderProfile();if(typeof renderInventory==='function')renderInventory();if(typeof updateMailBadge==='function')updateMailBadge();}catch(e){}}
function restoreFromServer(){return loadAccount(currentUser);}
const SHOP_CATALOG={};
function catalogItem(item){if(!item||!item.id)return null;const known=window.CHROMA_SHOP_CATALOG?.[item.id]||SHOP_CATALOG[item.id];return known&&known.price===Number(item.price)?known:null;}
async function purchaseShopItem(item){if(!canWrite())throw new Error(authUnavailableMessage());const valid=catalogItem(item);if(!valid)throw new Error('Cosmético inválido.');const ref=doc(db,'users',currentUser.uid);let next;await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error('Perfil não encontrado.');const d=snap.data(),shop={...defaultShop(),...(d.shop||{})},owned=Array.isArray(shop.owned)?shop.owned:[],level=Number(d.level||1);if(valid.levelOnly&&level<valid.levelOnly)throw new Error('Nível insuficiente para este cosmético.');if(owned.includes(valid.id))throw new Error('Este item já está desbloqueado.');if(Number(d.coins||0)<valid.price)throw new Error('Moedas insuficientes.');shop.owned=[...owned,valid.id];next={...d,coins:Number(d.coins)-valid.price,xp:Number(d.xp||0),level,rank:d.rank||'Prata I',cosmetics:shop.owned,equipped:shop.equipped,shop,updatedAt:serverTimestamp()};tx.set(ref,next,{merge:true});});writeLocal(next);refreshGameAfterCloud();return next;}
async function equipShopItem(itemId,type,equipped){if(!canWrite())throw new Error(authUnavailableMessage());const ref=doc(db,'users',currentUser.uid);let next;await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error('Perfil não encontrado.');const d=snap.data(),shop={...defaultShop(),...(d.shop||{})};if(!shop.owned.includes(itemId)&&equipped)throw new Error('Cosmético não desbloqueado.');shop.equipped={...shop.equipped,[type]:equipped};next={...d,shop,equipped:shop.equipped,cosmetics:shop.owned,updatedAt:serverTimestamp()};tx.set(ref,next,{merge:true});});writeLocal(next);refreshGameAfterCloud();return next;}
async function debitCoins(amount){if(!canWrite())throw new Error(authUnavailableMessage());const ref=doc(db,'users',currentUser.uid);let next;await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error('Perfil não encontrado.');const d=snap.data(),coins=Number(d.coins||0);if(coins<amount)throw new Error('Moedas insuficientes.');next={...d,coins:coins-amount,updatedAt:serverTimestamp()};tx.set(ref,next,{merge:true});});writeLocal(next);refreshGameAfterCloud();return next;}
window.chromaCloud={canWrite,persistState,syncToCloud,restoreFromServer,purchaseShopItem,equipShopItem,debitCoins,getUser:()=>currentUser,getAuthState:()=>authState,getWriteMessage:authUnavailableMessage,isAuthenticated:()=>authState==='AUTHENTICATED'&&!!currentUser};
window.chromaAuth={getState:()=>authState,getUser:()=>currentUser,isLoading:()=>authState==='AUTH_LOADING',isAuthenticated:()=>authState==='AUTHENTICATED'&&!!currentUser};
async function submitAuth(mode){await authPersistenceReady;const email=($('#accountEmail')?.value||'').trim(),password=$('#accountPassword')?.value||'';if(!email||!password){accountMessage('Informe e-mail e senha.',true);return;}try{$('#accountSubmit').disabled=true;if(mode==='signup'){const c=await createUserWithEmailAndPassword(auth,email,password);const name=($('#inName')?.value||'').trim();if(name)await updateProfile(c.user,{displayName:name});}else{await signInWithEmailAndPassword(auth,email,password);if(pendingGoogleCredential){await linkWithCredential(auth.currentUser,pendingGoogleCredential);pendingGoogleCredential=null;accountMessage('Google vinculado à sua conta.');}}$('#accountModal').classList.remove('on');}catch(e){accountMessage(friendlyError(e),true);}finally{$('#accountSubmit').disabled=false;}}
async function signInGoogle(){try{$('#accountGoogle').disabled=true;accountMessage('Abrindo o login do Google…');await signInWithPopup(auth,googleProvider);$('#accountModal').classList.remove('on');}catch(e){if(e.code==='auth/account-exists-with-different-credential'){pendingGoogleCredential=GoogleAuthProvider.credentialFromError(e);accountMessage('Esta conta já existe com e-mail e senha. Entre com e-mail e senha para vincular o Google.',true);}else accountMessage(friendlyError(e),true);}finally{$('#accountGoogle').disabled=false;}}
function bind(){updateAccountUI();$('#accountOpen')?.addEventListener('click',()=>{$('#accountModal').classList.add('on');accountMessage(currentUser?'Conta conectada.':'Entre para salvar seu progresso em qualquer celular.');});$('#accountClose')?.addEventListener('click',()=>$('#accountModal').classList.remove('on'));$('#accountSubmit')?.addEventListener('click',()=>submitAuth($('#accountMode').value));$('#accountGoogle')?.addEventListener('click',signInGoogle);$('#accountMode')?.addEventListener('change',e=>{const signup=e.target.value==='signup';$('#accountSubmit').textContent=signup?'Criar conta':'Entrar';$('#accountNameHint').hidden=!signup;});$('#accountForgot')?.addEventListener('click',async()=>{const email=($('#accountEmail')?.value||'').trim();if(!email){accountMessage('Digite seu e-mail primeiro.',true);return;}try{await sendPasswordResetEmail(auth,email);accountMessage('Link de recuperação enviado para seu e-mail.');}catch(e){accountMessage(friendlyError(e),true);}});$('#accountLogout')?.addEventListener('click',()=>signOut(auth));window.addEventListener('chroma-state-changed',()=>syncToCloud());}
bind();onAuthStateChanged(auth,user=>{const token=++authLoadToken;currentUser=user;accountReady=false;authLoadError='';authState=user?'AUTHENTICATED':'UNAUTHENTICATED';updateAccountUI();if(!user){accountMessage('Você não está conectado a uma conta.');return;}loadAccount(user,token).catch(e=>{if(token!==authLoadToken)return;accountReady=false;authLoadError=friendlyError(e);updateAccountUI();if(typeof window.renderSocial==='function')window.renderSocial();if(typeof window.renderClan==='function')window.renderClan();accountMessage(authLoadError,true);});});

/* ===== SOCIAL / AMIGOS / CLÃ — dados permanentes no Firestore ===== */

function socialProfileFromLocal(){
  const name=localStorage.getItem(keys.name)||currentUser?.displayName||'Jogador';
  const username=(localStorage.getItem(keys.username)||usernameFromUser(currentUser||{})).toLowerCase();
  let rank='Prata I'; try{if(typeof rankedStats==='function'&&typeof rankedTier==='function'){const t=rankedTier(rankedStats(name).points);rank=t.name+' '+t.level;}}catch(_){ }
  return {uid:currentUser.uid,username,usernameLower:username,name:name.slice(0,40),photo:localStorage.getItem(keys.photo)||'',rank,level:typeof levelFromXP==='function'?levelFromXP(Number(localStorage.getItem(keys.xp)||0)):1,clanId:localStorage.getItem('chroma-clan-id')||null};
}
async function publishSocialProfile(){
  if(!canWrite())throw new Error('Entre na conta para usar o Social.');
  const p=socialProfileFromLocal(), ref=doc(db,'publicProfiles',currentUser.uid), old=await getDoc(ref);
  await setDoc(ref,{...p,createdAt:old.exists()?(old.data().createdAt||serverTimestamp()):serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});
  return p;
}
function ensureSocial(){if(!canWrite())throw new Error(authUnavailableMessage());}
function friendKey(a,b){return [a,b].sort().join('__');}
async function searchSocialPlayers(term){
  ensureSocial(); const text=String(term||'').trim().toLowerCase().replace(/^@+/,''); if(text.length<2)return [];
  const q=query(collection(db,'publicProfiles'),where('usernameLower','>=',text),where('usernameLower','<=',text+'\uf8ff'),limit(12));
  const snap=await getDocs(q); return snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.uid!==currentUser.uid);
}
async function socialRequests(){
  ensureSocial();
  const [incoming,outgoing]=await Promise.all([
    getDocs(query(collection(db,'friendRequests'),where('toUid','==',currentUser.uid),limit(50))),
    getDocs(query(collection(db,'friendRequests'),where('fromUid','==',currentUser.uid),limit(50)))
  ]);
  const incomingDocs=incoming.docs.filter(d=>d.data().status==='pending'); const outgoingDocs=outgoing.docs.filter(d=>d.data().status==='pending');
  return {incoming:incomingDocs.map(d=>({id:d.id,...d.data()})),outgoing:outgoingDocs.map(d=>({id:d.id,...d.data()}))};
}
async function socialFriends(){
  ensureSocial(); const snap=await getDocs(query(collection(db,'friendships'),where('participants','array-contains',currentUser.uid),limit(100)));
  return snap.docs.map(d=>({id:d.id,...d.data()}));
}
async function sendSocialFriendRequest(target){
  ensureSocial(); if(!target?.uid||target.uid===currentUser.uid)throw new Error('Jogador inválido.');
  const existing=await getDocs(query(collection(db,'friendRequests'),where('fromUid','==',currentUser.uid),where('toUid','==',target.uid),where('status','==','pending'),limit(1)));
  if(!existing.empty)throw new Error('Solicitação já enviada.');
  const reverse=await getDocs(query(collection(db,'friendRequests'),where('fromUid','==',target.uid),where('toUid','==',currentUser.uid),where('status','==','pending'),limit(1)));
  if(!reverse.empty)throw new Error('Este jogador já enviou uma solicitação.');
  const friendships=await getDocs(query(collection(db,'friendships'),where('participants','array-contains',currentUser.uid),limit(100)));
  if(friendships.docs.some(d=>(d.data().participants||[]).includes(target.uid)))throw new Error('Vocês já são amigos.');
  const me=await getDoc(doc(db,'publicProfiles',currentUser.uid));
  const from=me.exists()?me.data():await publishSocialProfile();
  const ref=await addDoc(collection(db,'friendRequests'),{fromUid:currentUser.uid,toUid:target.uid,from:{username:from.username,name:from.name,photo:from.photo||'',rank:from.rank||'Prata I',level:Number(from.level||1)},to:{username:target.username,name:target.name,photo:target.photo||'',rank:target.rank||'Prata I',level:Number(target.level||1)},status:'pending',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});
  return {id:ref.id};
}
async function respondSocialFriendRequest(requestId,accept){
  ensureSocial(); const ref=doc(db,'friendRequests',requestId); let result;
  await runTransaction(db,async tx=>{
    const snap=await tx.get(ref); if(!snap.exists())throw new Error('Solicitação não encontrada.');
    const r=snap.data(); if(r.toUid!==currentUser.uid||r.status!=='pending')throw new Error('Solicitação indisponível.');
    if(!accept){tx.update(ref,{status:'declined',updatedAt:serverTimestamp()});result={status:'declined'};return;}
    const fid=friendKey(r.fromUid,r.toUid),fref=doc(db,'friendships',fid);
    tx.set(fref,{participants:[r.fromUid,r.toUid],profiles:{[r.fromUid]:r.from,[r.toUid]:r.to},createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});
    tx.update(ref,{status:'accepted',updatedAt:serverTimestamp()}); result={status:'accepted',id:fid};
  }); return result;
}
async function removeSocialFriend(friendshipId){ensureSocial();await deleteDoc(doc(db,'friendships',friendshipId));}
async function readSocialPublicProfile(uid){ensureSocial();const s=await getDoc(doc(db,'publicProfiles',uid));if(!s.exists())throw new Error('Perfil não encontrado.');return {uid,...s.data()};}
async function createSocialClan(name,icon='shield'){
  ensureSocial(); const clean=String(name||'').trim().replace(/\s+/g,' '); if(clean.length<3||clean.length>24||!/^[\p{L}\p{N} _-]+$/u.test(clean))throw new Error('Use um nome de clã entre 3 e 24 caracteres.');
  const me=await getDoc(doc(db,'publicProfiles',currentUser.uid)); if(!me.exists())await publishSocialProfile();
  const myUser=await getDoc(doc(db,'users',currentUser.uid)); if((myUser.data()?.clanId))throw new Error('Você já está em um clã.');
  const dup=await getDocs(query(collection(db,'clans'),where('nameLower','==',clean.toLowerCase()),limit(1))); if(!dup.empty)throw new Error('Esse nome de clã já está em uso.');
  const clan={name:clean,nameLower:clean.toLowerCase(),icon:['shield','sparkles','flame','crown','star'].includes(icon)?icon:'shield',leaderId:currentUser.uid,level:1,xp:0,xpToNext:100,memberCount:1,members:{[currentUser.uid]:{uid:currentUser.uid,role:'leader',joinedAt:serverTimestamp(),contributionXp:0}},missions:[],rewards:[],events:[],createdAt:serverTimestamp(),updatedAt:serverTimestamp()};
  let cid; await runTransaction(db,async tx=>{const ref=doc(collection(db,'clans'));cid=ref.id;tx.set(ref,clan);tx.update(doc(db,'users',currentUser.uid),{clanId:cid,clanRole:'leader',updatedAt:serverTimestamp()});tx.set(doc(db,'publicProfiles',currentUser.uid),{clanId:cid,clanName:clean,updatedAt:serverTimestamp()},{merge:true});});
  return {id:cid,...clan};
}
async function listSocialClans(term=''){
  ensureSocial(); const text=String(term||'').trim().toLowerCase(); const snap=text?await getDocs(query(collection(db,'clans'),where('nameLower','>=',text),where('nameLower','<=',text+'\uf8ff'),limit(20))):await getDocs(query(collection(db,'clans'),orderBy('createdAt','desc'),limit(20))); return snap.docs.map(d=>({id:d.id,...d.data()}));
}
async function getSocialClan(id){ensureSocial();const s=await getDoc(doc(db,'clans',id));if(!s.exists())throw new Error('Clã não encontrado.');return {id:s.id,...s.data()};}
async function joinSocialClan(id){ensureSocial();await runTransaction(db,async tx=>{const cref=doc(db,'clans',id),uref=doc(db,'users',currentUser.uid),pref=doc(db,'publicProfiles',currentUser.uid);const [cs,us]=await Promise.all([tx.get(cref),tx.get(uref)]);if(!cs.exists())throw new Error('Clã não encontrado.');if(us.data()?.clanId)throw new Error('Você já está em um clã.');const c=cs.data();tx.update(cref,{['members.'+currentUser.uid]:{uid:currentUser.uid,role:'member',joinedAt:serverTimestamp(),contributionXp:0},memberCount:Number(c.memberCount||0)+1,updatedAt:serverTimestamp()});tx.update(uref,{clanId:id,clanRole:'member',updatedAt:serverTimestamp()});tx.set(pref,{clanId:id,clanName:c.name,updatedAt:serverTimestamp()},{merge:true});});}
async function leaveSocialClan(id){ensureSocial();await runTransaction(db,async tx=>{const cref=doc(db,'clans',id),uref=doc(db,'users',currentUser.uid),pref=doc(db,'publicProfiles',currentUser.uid),cs=await tx.get(cref);if(!cs.exists())throw new Error('Clã não encontrado.');const c=cs.data();if(c.leaderId===currentUser.uid)throw new Error('O líder precisa transferir a liderança antes de sair.');tx.update(cref,{['members.'+currentUser.uid]:null,memberCount:Math.max(0,Number(c.memberCount||1)-1),updatedAt:serverTimestamp()});tx.update(uref,{clanId:null,clanRole:null,updatedAt:serverTimestamp()});tx.set(pref,{clanId:null,clanName:null,updatedAt:serverTimestamp()},{merge:true});});}
window.chromaSocial={publishSocialProfile,searchPlayers:searchSocialPlayers,requests:socialRequests,friends:socialFriends,sendRequest:sendSocialFriendRequest,respondRequest:respondSocialFriendRequest,removeFriend:removeSocialFriend,publicProfile:readSocialPublicProfile,createClan:createSocialClan,listClans:listSocialClans,getClan:getSocialClan,joinClan:joinSocialClan,leaveClan:leaveSocialClan,isReady:()=>canWrite()};
