import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, sendPasswordResetEmail, updateProfile } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';

const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getFirestore(app);
let currentUser=null, syncTimer=null, applyingRemote=false;
const $=s=>document.querySelector(s);
const keys={coins:'chroma-coins',xp:'chroma-xp',shop:'chroma-shop',name:'chroma-name',username:'chroma-username',photo:'chroma-profile-photo',gender:'chroma-profile-gender',streak:'chroma-daily-streak',levelRewards:'chroma-level-rewards',redeemedCodes:'chroma-redeemed-codes',missions:'chroma-missions',ranking:'chroma-ranking',ranked:'chroma-ranked',mailRead:'chroma-mail-read',friends:'chroma-friends'};
function json(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch(e){return fallback;}}
function localState(){return {coins:Number(localStorage.getItem(keys.coins)||0)||0,xp:Number(localStorage.getItem(keys.xp)||0)||0,shop:json(keys.shop,{owned:[],equipped:{profile:'',cards:[],'name-effect':''},potions:[]}),name:localStorage.getItem(keys.name)||'',username:localStorage.getItem(keys.username)||'',photo:localStorage.getItem(keys.photo)||'',gender:localStorage.getItem(keys.gender)||'',streak:json(keys.streak,{day:0,lastClaim:null}),levelRewards:json(keys.levelRewards,[]),redeemedCodes:json(keys.redeemedCodes,[]),missions:json(keys.missions,null),ranking:json(keys.ranking,[]),ranked:json(keys.ranked,[]),mailRead:json(keys.mailRead,[]),friends:json(keys.friends,{friends:[],requests:[],sent:[]})};}
function writeLocal(data){if(data.coins!=null)localStorage.setItem(keys.coins,String(data.coins));if(data.xp!=null)localStorage.setItem(keys.xp,String(data.xp));for(const k of ['shop','streak','levelRewards','redeemedCodes','missions','ranking','ranked','mailRead','friends'])if(data[k]!==undefined)localStorage.setItem(keys[k],JSON.stringify(data[k]));for(const k of ['name','username','photo','gender'])if(data[k]!==undefined)localStorage.setItem(keys[k],data[k]||'');}
function accountMessage(text,error=false){const el=$('#accountMsg');if(el){el.textContent=text;el.className='account-msg'+(error?' error':'');}}
function friendlyError(e){const code=e&&e.code||'';return code.includes('email-already-in-use')?'Este e-mail já está cadastrado.':code.includes('invalid-credential')||code.includes('wrong-password')||code.includes('user-not-found')?'E-mail ou senha incorretos.':code.includes('weak-password')?'A senha precisa ter pelo menos 6 caracteres.':code.includes('invalid-email')?'Digite um e-mail válido.':e.message||'Não foi possível concluir a operação.';}
function updateAccountUI(){window.firebaseCurrentUserEmail=currentUser&&currentUser.email||'';const logged=!!currentUser;const status=$('#accountStatus'),open=$('#accountOpen'),out=$('#accountLogout');if(status)status.textContent=logged?'Conta: '+(currentUser.email||'conectada'):'Progresso local — entre para salvar na nuvem';if(open)open.textContent=logged?'Gerenciar conta':'Entrar ou criar conta';if(out)out.hidden=!logged;}
async function syncToCloud(){if(!currentUser||applyingRemote)return;const data=localState();await setDoc(doc(db,'users',currentUser.uid),{...data,email:currentUser.email||'',updatedAt:serverTimestamp()},{merge:true});}
function queueSync(){if(!currentUser||applyingRemote)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncToCloud().catch(()=>{}),700);}
function refreshGameAfterCloud(){try{if($('#inName'))$('#inName').value=localStorage.getItem(keys.name)||'';if($('#profileGender'))$('#profileGender').value=localStorage.getItem(keys.gender)||'';const photo=localStorage.getItem(keys.photo)||'';if(photo&&$('#profilePreview'))$('#profilePreview').innerHTML='<img src="'+photo.replace(/"/g,'&quot;')+'" alt="Foto de perfil">';if(typeof updateCoinHud==='function')updateCoinHud(false);if(typeof renderProfileXP==='function')renderProfileXP();if(typeof updateModeLockUI==='function')updateModeLockUI();if(typeof applyCosmetics==='function')applyCosmetics();if(typeof renderShop==='function')renderShop();if(typeof renderProfile==='function')renderProfile();if(typeof renderInventory==='function')renderInventory();if(typeof updateMailBadge==='function')updateMailBadge();}catch(e){}}
async function loadAccount(user){currentUser=user;updateAccountUI();if(!user)return;const ref=doc(db,'users',user.uid),snap=await getDoc(ref);if(snap.exists()){applyingRemote=true;writeLocal(snap.data());applyingRemote=false;refreshGameAfterCloud();}else{await syncToCloud();}accountMessage('Conectado. Seu progresso será salvo na nuvem.');}
async function submitAuth(mode){const email=($('#accountEmail')?.value||'').trim(),password=$('#accountPassword')?.value||'';if(!email||!password){accountMessage('Informe e-mail e senha.',true);return;}try{$('#accountSubmit').disabled=true;if(mode==='signup'){const c=await createUserWithEmailAndPassword(auth,email,password);const name=($('#inName')?.value||'').trim();if(name)await updateProfile(c.user,{displayName:name});}else await signInWithEmailAndPassword(auth,email,password);$('#accountModal').classList.remove('on');}catch(e){accountMessage(friendlyError(e),true);}finally{$('#accountSubmit').disabled=false;}}
function bind(){updateAccountUI();$('#accountOpen')?.addEventListener('click',()=>{$('#accountModal').classList.add('on');accountMessage(currentUser?'Conta conectada.':'Entre para salvar seu progresso em qualquer celular.');});$('#accountClose')?.addEventListener('click',()=>$('#accountModal').classList.remove('on'));$('#accountSubmit')?.addEventListener('click',()=>submitAuth($('#accountMode').value));$('#accountMode')?.addEventListener('change',e=>{const signup=e.target.value==='signup';$('#accountSubmit').textContent=signup?'Criar conta':'Entrar';$('#accountNameHint').hidden=!signup;});$('#accountForgot')?.addEventListener('click',async()=>{const email=($('#accountEmail')?.value||'').trim();if(!email){accountMessage('Digite seu e-mail primeiro.',true);return;}try{await sendPasswordResetEmail(auth,email);accountMessage('Link de recuperação enviado para seu e-mail.');}catch(e){accountMessage(friendlyError(e),true);}});$('#accountLogout')?.addEventListener('click',()=>signOut(auth));window.addEventListener('chroma-state-changed',queueSync);}
bind();onAuthStateChanged(auth,user=>loadAccount(user).catch(e=>accountMessage('Não foi possível carregar a conta.',true)));
